# Generated by Django 4.2.1 on 2024-02-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_dashboarddata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='intensity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='likelihood',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='relevance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
