# Generated by Django 4.2.1 on 2024-02-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_alter_dashboarddata_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='end_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
